export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  OPERATOR = 'OPERATOR',
  TECHNICIAN = 'TECHNICIAN',
  READ_ONLY = 'READ_ONLY',
  COST_ANALYST = 'COST_ANALYST',
}

export enum WorkOrderStatus {
  NEW = 'NEW',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_ON_OPS = 'WAITING_ON_OPS',
  WAITING_ON_PARTS = 'WAITING_ON_PARTS',
  RESOLVED = 'RESOLVED',
  VERIFIED = 'VERIFIED',
  CLOSED = 'CLOSED',
  ESCALATED = 'ESCALATED',
  CANCELLED = 'CANCELLED',
}

export enum WorkOrderPriority {
  IMMEDIATE = 'IMMEDIATE',
  URGENT = 'URGENT',
  SCHEDULED = 'SCHEDULED',
  DEFERRED = 'DEFERRED',
}

export enum WorkOrderType {
  REACTIVE = 'REACTIVE',
  PREVENTIVE = 'PREVENTIVE',
  INSPECTION = 'INSPECTION',
  CORRECTIVE = 'CORRECTIVE',
}

export enum SiteType {
  WELL_SITE = 'WELL_SITE',
  PLANT = 'PLANT',
  BUILDING = 'BUILDING',
  APARTMENT = 'APARTMENT',
  LINE = 'LINE',
  SUITE = 'SUITE',
  COMPRESSOR_STATION = 'COMPRESSOR_STATION',
  TANK_BATTERY = 'TANK_BATTERY',
  SEPARATOR = 'SEPARATOR',
  OTHER = 'OTHER',
}

export enum Permission {
  CAN_VIEW_COSTS = 'CAN_VIEW_COSTS',
  CAN_MANAGE_BUDGET = 'CAN_MANAGE_BUDGET',
  CAN_VIEW_INCENTIVES = 'CAN_VIEW_INCENTIVES',
  CAN_MANAGE_INVENTORY = 'CAN_MANAGE_INVENTORY',
  CAN_MANAGE_USERS = 'CAN_MANAGE_USERS',
  CAN_VIEW_AUDIT_LOG = 'CAN_VIEW_AUDIT_LOG',
  CAN_MANAGE_PM_TEMPLATES = 'CAN_MANAGE_PM_TEMPLATES',
}

export enum TimelineEventType {
  STATUS_CHANGE = 'STATUS_CHANGE',
  MESSAGE = 'MESSAGE',
  ATTACHMENT = 'ATTACHMENT',
  PARTS_ADDED = 'PARTS_ADDED',
  LABOR_LOGGED = 'LABOR_LOGGED',
  NOTE = 'NOTE',
  ASSIGNMENT_CHANGE = 'ASSIGNMENT_CHANGE',
  SLA_BREACH = 'SLA_BREACH',
  ESCALATION = 'ESCALATION',
  GPS_SNAPSHOT = 'GPS_SNAPSHOT',
  SAFETY_FLAG_SET = 'SAFETY_FLAG_SET',
}

export enum SLAEventType {
  ACK_BREACH = 'ACK_BREACH',
  FIRST_UPDATE_BREACH = 'FIRST_UPDATE_BREACH',
  RESOLVE_BREACH = 'RESOLVE_BREACH',
  MANUAL_ESCALATION = 'MANUAL_ESCALATION',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
}

export enum TransactionType {
  IN = 'IN',
  OUT = 'OUT',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum RecurrenceType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM_DAYS = 'CUSTOM_DAYS',
  METER_BASED = 'METER_BASED',
}

export enum OnCallPriority {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
}
